### PR TITLE
fix: playwright test - no tests found

### LINKED ISSUE #152: playwright test - no tests found
## deskripsi
muncul `no tests found.` ketika menjalankan command
```shell
pnpm test
```

## screenshot
pnpm-before

### PR DESCRIPTION
**Pull request by depapp**
fix #152 

pnpm-after

### CODE REVIEW

**Comment by depapp** [comment]
maaf mas @rizafahmi boleh di share kah deploy failed nya karena apa? 
saya gk ada akses buat inspect 🙏🏻 

image

**Comment by rizafahmi** [comment]
Sepertinya masalah versi?

```
error during build:
--
Error: @sveltejs/adapter-vercel >=2.x (possibly installed through @sveltejs/adapter-auto) requires @sveltejs/kit version 1.5 or higher. Either downgrade the adapter or upgrade @sveltejs/kit
at Object.adapt (file:///vercel/path0/node_modules/.pnpm/@sveltejs+adapter-vercel@2.0.4_@sveltejs+kit@1.0.1/node_modules/@sveltejs/adapter-vercel/index.js:30:11)
at Object.adapt (file:///vercel/path0/node_modules/.pnpm/@sveltejs+adapter-auto@1.0.0_@sveltejs+kit@1.0.1/node_modules/@sveltejs/adapter-auto/index.js:103:19)
at adapt (file:///vercel/path0/node_modules/.pnpm/@sveltejs+adapter-auto@1.0.0_@sveltejs+kit@1.0.1/node_modules/@sveltejs/adapter-auto/index.js:114:31)
at async adapt (file:///vercel/path0/node_modules/.pnpm/@sveltejs+kit@1.0.1_svelte@3.55.0+vite@4.0.3/node_modules/@sveltejs/kit/src/core/adapt/index.js:28:2)
at async Object.handler (file:///vercel/path0/node_modules/.pnpm/@sveltejs+kit@1.0.1_svelte@3.55.0+vite@4.0.3/node_modules/@sveltejs/kit/src/exports/vite/index.js:611:6)
at async PluginDriver.hookParallel (file:///vercel/path0/node_modules/.pnpm/rollup@3.7.5/node_modules/rollup/dist/es/shared/rollup.js:23373:17)
at async Object.close (file:///vercel/path0/node_modules/.pnpm/rollup@3.7.5/node_modules/rollup/dist/es/shared/rollup.js:24725:13)
at async Promise.all (index 0)
at async build (file:///vercel/path0/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:44326:13)
at async CAC.<anonymous> (file:///vercel/path0/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/cli.js:808:9)
ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1
```

**Comment by depapp** [comment]
fixed ya mas @rizafahmi https://github.com/rizafahmi/carikerja/pull/154/commits/1c720b8ab38e50a9f6d6ba9b7d47fab90a0190c0
mohon review nya kembali 🙏🏻

**Comment by rizafahmi** [comment]
Mantap. Terimakasih banyak mas @depapp 🙇

**Pull request merged**
